#!/bin/bash
# use bash to prevent some problem due to different behaviors on different OS

# Get the absolute path of this script
# from: http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
BASEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null && pwd )"

# From: https://github.com/vinta/HAL-9000/blob/master/bin/open-the-pod-bay-doors
if which tput >/dev/null 2>&1; then
    ncolors=$(tput colors)
fi
# Check if stdout is a terminal & support color 
if [ -t 1 ] && [ -n "$ncolors" ] && [ "$ncolors" -ge 8 ]; then
    BLUE="$(tput setaf 4)"
    GREEN="$(tput setaf 2)"
    RED="$(tput setaf 1)"
    YELLOW="$(tput setaf 3)"
    BOLD="$(tput bold)"
    NORMAL="$(tput sgr0)"
else
    BLUE=""
    GREEN=""
    RED=""
    YELLOW=""
    BOLD=""
    NORMAL=""
fi

# Show message and wait user's answer 
confirm_prompt(){
    read -r -p "$1 ${BOLD}[y/N]${NORMAL}: " yn   
    case $yn in
        [yY][eE][sS]|[yY]) return 0 ;;  #TRUE      
        *) return 1 ;;                  #FALSE
    esac
}

create_soft_link(){
    if [ "$#" -ne 2 ]; then
        echo
        echo "@create_soft_link(): parameter should be (1) source (2) target"
        return 1
    fi    
    
    echo
    echo "try to link ${BOLD}$2 ${NORMAL}to ${BOLD}$1${NORMAL}"
    if [ -L $2 ]; then
        if confirm_prompt "->link: $2 already exists, replace it? "; then
            ln -s -f $1 $2
            echo "-> ok, replace $1 "
        fi
    elif [ -f $2 ]; then
        if confirm_prompt "->file: $2 already exists, backup it and create link to $1? "; then
            mv -i $2 "$2.backup"
            ln -s $1 $2
        fi
    elif [ -d $2 ]; then
        if confirm_prompt "->dir: $2 already exist, rename the folder and create link to $1? "; then
            mv -i $2 "$2.backup"
            ln -s $1 $2
        fi
    else
        ln -s $1 $2
        echo "-> ok, create the link"
    fi
}

# give name of dotfile in dotfiles folder, create link in HOME to it   
create_soft_link_by_name(){
    if [ "$#" -ne 1 ]; then
        echo
        echo "@create_soft_link_by_name(): parameter should be name of dotfile"
        return 1
    fi    
    
    create_soft_link "$BASEDIR/$1" "$HOME/$1"
}

copy_safely(){
    if [ "$#" -ne 2 ]; then
        echo
        echo "@copy_safely(): parameter should be (1) source (2) target"
        return 1
    fi        
    
    echo
    echo "try to create target $2"
    if [ -f $2 ]; then
        if confirm_prompt "->file: $2 already exist, replace it?"; then
            cp -f $1 $2
        fi
    else
        cp $1 $2
    fi
}

echo "Hello $USER!"
echo "Now install.sh will try to create/link necessary dotfiles under $HOME"
# bash setting
copy_safely "$BASEDIR/.bashrc.skeleton" "$BASEDIR/.bashrc"
create_soft_link_by_name .profile
create_soft_link_by_name .bashrc
create_soft_link_by_name .inputrc

# screen setting
create_soft_link_by_name .screenrc

# tmux setting 
create_soft_link_by_name .tmux.conf

# vim setting
## since Vim 7.4, user can put .vimrc inside $HOME/.vim/ folder 
## but for compatiability, still create a link in user'home folder 
create_soft_link_by_name ".vim"
create_soft_link "$BASEDIR/.vim/vimrc" "$HOME/.vimrc"
        
# neovim setting 
if `command -v nvim > /dev/null 2>&1` \
    || confirm_prompt "you haven't install neovim, still create its configuration links?" ; then
    
    echo "try to link $HOME/.config/nvim & $HOME/.config/nvim/init.vim"
    if [ -L ~/.config ]; then
        mkdir ~/.config
    fi

    create_soft_link "$BASEDIR/.vim" "$HOME/.config/nvim"
    create_soft_link "$BASEDIR/.vim/vimrc" "$BASEDIR/.vim/init.vim"
fi


# parameter is the target URL
install_bash_plugin_from_url(){
    if [ "$#" -ne 1 ]; then
        echo "@install_bash_plugin_from_url(): parameter should be URL of bash plugin"
        return 1
    fi
    
    BASH_PLUGIN_NAME="$( echo $1 | awk -F/ '{print $NF}')" 
    
    echo "-> try to get ${BOLD}$1"
    curl "$1" -o "$BASEDIR/$BASH_PLUGIN_NAME"           
    echo "# use $BASH_PLUGIN_NAME from $1" >> $BASEDIR/.bashrc
    echo "# --below line is generated by $BASEDIR/install.sh--" >> $BASEDIR/.bashrc
    echo "[[ -s $BASEDIR/$BASH_PLUGIN_NAME ]] && source $BASEDIR/$BASH_PLUGIN_NAME " >> $BASEDIR/.bashrc
    echo "" >> $BASEDIR/.bashrc
}


# try to get bash plugin
# 1. sensible.bash from https://github.com/mrzool/bash-sensible
# 2. commacd.bash from https://github.com/shyiko/commacd
if `command -v curl > /dev/null 2>&1` ; then 
    mv $BASEDIR/.bashrc $BASEDIR/.bashrc.backup

    echo
    echo "try to install bash plugins"
    
    if confirm_prompt "-> modify .bashrc to use sensible.bash? " ; then
        install_bash_plugin_from_url \
            "https://raw.githubusercontent.com/mrzool/bash-sensible/master/sensible.bash" 
    fi

    if confirm_prompt "-> modify .bashrc to use commacd.bash? " ; then
        install_bash_plugin_from_url \
            "https://raw.githubusercontent.com/shyiko/commacd/master/commacd.bash"
    fi


    cat $BASEDIR/.bashrc.backup >> $BASEDIR/.bashrc
    rm -f $BASEDIR/.bashrc.backup
else
    echo "couldn't find ${BOLD}curl${NORMAL}, so that didn't install bash plugins"
fi


